# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 13:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(verbose_name='/static/images')),
                ('label', models.SmallIntegerField(choices=[(0, 'not ripe'), (1, 'ripe'), (2, 'too ripe')])),
                ('label_is_right', models.NullBooleanField(default=False)),
                ('tmstp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ML_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vals', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spectrum', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('fruit', models.IntegerField()),
                ('label', models.SmallIntegerField(choices=[(0, 'not ripe'), (1, 'ripe'), (2, 'too ripe')])),
                ('gps', models.TextField(null=True)),
                ('tmstp', models.DateTimeField(null=True)),
                ('image_path', models.FilePathField(null=True, verbose_name='/static/images')),
                ('label_is_right', models.NullBooleanField(default=False)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frutopy.ML_Model')),
            ],
            options={
                'ordering': ['-tmstp'],
            },
        ),
        migrations.CreateModel(
            name='SP_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vals', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sp_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frutopy.SP_Model'),
        ),
    ]
